### ISSUE TITLE
maybeEndSync should return root ref

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-client#81]
Once maybeEndSync returns an empty list of replays we should include the root ref of master so that we can do a check change on the client.'

If we do not have this we will need to call `getRoot`.

**Comment by arv** [comment]
Actually, this is just the ref we from beginSync or the ref we get back from commits when replaying.

@aboodman @phritz Just to verify my thinking.

**Comment by arv** [comment]
Once the last `"maybeEndSync"` (the one with no more replays) is done we want to get the head `Ref` of  the master branch so that we can see if the there has been any changes. One way to do this is to call `"getRoot"` again which returns the `HeadHash()`. I think this is not needed because we can use the `Ref` returned from the last `Commit` or the `SyncHead` from `"beginSync"` if there were no commits to replay.

**Comment by aboodman** [comment]
looks right.

**Comment by phritz** [comment]
yes, sounds right
